#!/bin/bash

status="first"
current=

# Because npm<2.7 does not support scoped package, this tool gets the command
# of `scripts.test` in package.json and runs it for a scoped package.
command=$(node -e "console.log(require('./package').scripts.test)")
command=node_modules/.bin/${command}

for version in `nodebrew list`; do
  if [ "${status}" == "end" ]; then
    current=${version}
    break

  elif [ "${version}" == "current:" ]; then
    status="end"
    continue

  elif [ "${status}" == "skip" ]; then
    continue

  elif [ "${status}" == "first" ]; then
    status=

  else
    read -p "Continue? (Y/n) " userinput
    if [ "${userinput}" == "n" ]; then
      status="skip"
      continue
    fi
  fi

  nodebrew use ${version}
  node -v
  npm -v
  ${command}
done

echo "Back to ${current}"
nodebrew use ${current}
