#!/bin/bash

command=$(node -e "console.log(require('./package').scripts.test)")
exename=$(echo ${command} | cut -f 1 -d " ")
if [ -f node_modules/.bin/${exename} ]; then
  command=node_modules/.bin/${command}
fi

current=$(nodebrew list | tail -n 1 | sed 's/^current: *//')
for version in $(nodebrew list | sed '$d'); do
  nodebrew use ${version}
  node -v
  npm -v
  ${command}
  exitcd=$?
  if [[ ${exitcd} -gt 0 ]]; then
    read -p "Continue? (Y/n) " userinput
    if [ "$(echo ${userinput} | tr '[:upper:]' '[:lower:]')" == "n" ]; then
      break
    fi
  fi
done

echo "Back to ${current}"
nodebrew use ${current}
