#!/bin/bash

command=$(node -e "console.log(require('./package').scripts.test)")
exename=$(echo ${command} | cut -f 1 -d " ")
if [ -f node_modules/.bin/${exename} ]; then
  command=node_modules/.bin/${command}
fi

function extract_version() {
  sed 's|^[> ] *||' | sed 's|  *(.*$||'
}

function current_version() {
  nodist list | grep '^>' | extract_version
}

current=$(current_version)

for version in $(nodist list | tail -n +2 | extract_version); do
  nodist ${version}
  nodist npm match
  node -v
  npm -v
  ${command}
  exitcd=$?
  if [[ $exitcd -gt 0 ]]; then
    read -p "Continue? (Y/n) " userinput
    if [ "$(echo ${userinput} | tr '[:upper:]' '[:lower:]')" == "n" ]; then
      break
    fi
  fi
done

echo "Back to ${current}"
nodist ${current}

