#!/bin/bash

status="first"
current=
command=$(node -e "console.log(require('./package').scripts.test)")
command=node_modules/.bin/${command}

function extract_version() {
  sed 's|^[> ] *||' | sed 's|  *(.*$||'
}

function current_version() {
  nodist list | grep '^>' | extract_version
}

current=`current_version`

for v in `nodist list | tail -n +2 | extract_version`; do
  if [ "${status}" != "first" ]; then
    read -p "Continue? (Y/n) " userinput
    if [ "${userinput}" == "n" ]; then
      break
    fi
  fi
  status=""

  nodist ${v}
  node -v
  npm -v
  node ${command}
done

echo "Back to ${current}"
nodist ${current}

